---
title: "Comparisons of dimensionality reduction methods"
author: "Emilie Mathian"
date: "6/18/2019"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: united
---

# Centrality preservation 
## Centrality preservation main function `CP_main`

### Description 
 
This function allows to calculate CP values for a list of data frames given as input. If a reference data frame is defined then the CP values are going to be compute and statistics and graphics could be eventually computed. 

### Usage

`CP_main <- function(l_data , list_K , dataRef = NULL , colnames_res_df = NULL , filename = NULL , graphics = FALSE, stats = FALSE)`

### Arguments

* **l_data** : list of data frames whose structure is :

| Sample_ID | x       | y        | ... |
|-----------|---------|----------|-----|
| MYID      | x_coord | y_coords | ... |

These data frames contain samples' coordinates which could be defined in $\mathbb{R^n}$. *The Sample_ID vector have to contain characters and not factors.*

* **listK** : list k values

* **dataref** : data frame of reference whose strucuture is the same as define above. If this argument is not defined then statistics and plot cannot be computed.

* **colnames_res_df** : This optional argument allows to specify colnames of the returned data frame and also plot's legend. If this argument is unsecified then the default values will be  : V1,V2, ..., Vn (where $n$ is the length of `l_data`). 

* **filename** : This optional arguement allows to define the filename in which results will be written. If this argument is unspecified then results will be returned and not written. If users choose a filename that ever exits in the current directory a incrementation to the filename will be done.

* **graphics** : This boolean argument allows to computes plots. This option is available only if `dataref` is defined. Indeed the plot is the means by k levels of the absolute differences between CP values caculated according each data frame defined in `l_data`, and the reference CP values.

* **stats** : As previously `stats` option allows to run statistic tests only if `dataref` is defined. If only two data frames were given as input via `l_data` then a Wilcoxon test will be computed to compare the distribution of the means by k levels of the absolute differences between CP values calculated for this two method and reference ones. If more than two methods were defined then Wilcoxon paired tests are done.

### Details 

* CP values' calcul are computed in parallel according the list of k levels. Furthermore in order to compute graphics and statistics a inner join between data frames will be done according the samples' ID.
* Wilcoxon's tests assume that data are non independent.
* On the graphic data are center, and scaled.

### Value 

According options activated the list returned contains the following elements :

* **CP_Data_frame** : data frame containing a column with the samples' Id, a column correspoding to the levels k, and $n$ colunms of CP values, more one if `dataref` is defined. This data frame is written in `filename`.

* **CP_Diff_mean_by_K** : data frame containing the means by k levels of the absolute differences between CP values caculated according each data frame defined in `l_data`, and the ones resulting from the reference data frame.

* **Wilcoxon_test** : Results of the Wilcoxon test.

* **Paired_wilocoxon_test** : Matrix containing paired Wilcoxon tests p.values adjusted by the Bonferroni method.


[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Centrality preservation : graphical description by k level `CP_graph_by_k`

### Description 
 
This function allows to draw a graphic, representing the means by k level of the absolute differences between CP values previously calculated and the ones given as references (cf : graphic returned by function`CP_main`).

### Usage

`CP_graph_by_k  <- function (data_CP,  ref_CP_data, Names = NULL, list_col = NULL, log = FALSE)`

### Arguments

* **data_CP** : data frame containing samples' CP values for $k$ levels. This data frame has the same structure as the one returned by the function `CP_main`, *i.e* : 

| Sample_ID | K         | CP1     | CP2     | ... |
|-----------|-----------|---------|---------|-----|
| MYID      | 1st_level | CP1_id1 | CP2_id1 | ... |

* **ref_CP_data** : Refence CP values data frame built as described above.

* **Names** : This optional argument allows to specify the legend. If it was not defined `data_CP` colnames will be used.

* **list_col** : This optional argument allows to speficy colors, otherwise the list of colors defined in the global environnement.

* **log**  : Boolean argument that allows a logarithmic represention if it is set to TRUE.
 
### Value 

A ggplot is printed and returned.

### Detail 

Data are scaled before to be ploted.

### See also 

`CP_main`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Centrality calculation `CP_calcul`

### Description 

This function allows to calculed the centrality values of points which could be defined in $\mathbb{R}^N$. For a point $j$ the centrality formula is : 

$$CP^d_k(j) = \sum_{1\leq i \leq N} k-\rho^d_i(j)$$
For the scale $k$, and for dimension $d$, $j$'s centrality is defined as the sum of differences between $k$ and $\rho^d_i(j)$, which is the rank of $j$ in the $k-$neighborhood of $i$.

### Usage

`CP_calcul <- function(data, list_K, parallel = TRUE)` 

### Arguments

* **data** : **data table** containing samples' ID  and their coordinates in  $\mathbb{R}^N$

* **list_K** : list of k levels according the ones CP values were calculated.

### Detail 

* This fonction use parallel calculation. 
* Becarful to the class of the data given as input.

### Value 

A data frame containing three columns : one  with the samples' Id, another one with corresponding levels k, and a third one with CP values.

### See also 

`CP_main`


## Centrality calculation internal function `CP_calcul_intern`

### Description 

This function is the same than `CP_calcul` but it is adapted for `CP_main`. Please use `CP_calcul`.

*I have to fix some errors to make `CP_calcul` functional for running with `CP_main`*

### See also 

`CP_calcul`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Centrality preservation permutation test `CP_permutation_test`

### Description 
This function calculates the means by k level of the absolute differences between CP values resulting from two methods such as :
$$DCP_k = \sum_{i = 1}^N (|CP_i^{d1} - CP^{d2}_i|)$$
Where $N$ is the number of sample, $d1$ is the dimensional space of the first method and reciprocally for $d2$ .
Then this function tests the following hypothesis :

$DCP_k$ values calculated on real data have the same mean rank as the one expected if data coordinates where randomly distributed.

After $n$ permutation a Willcoxon test is done.

### Usage

`CP_permutation_test <- function(data, data_ref, list_K, n=30, graph = TRUE)` 

### Arguments

* **data** : data frame containing samples' ID  and their coordinates in  $\mathbb{R}^N$.

* **data_ref** : data frame with the same features as those defined above.

* **list_K** : list of k levels according the ones CP values are calculated.

* **n** : optional numeric argument defining the number of simulations that will be done, because the computation could be long a warning message is printed if $n$ is higher than 30.

* **graph** : optional boolean argument specifying if a plot must be computed or not. 

### Value 

A ggplot willl be displayed, on this grapic the gray lines correpond to the simulations, the green one to the mean distribution resulting from the simulations, and the red one to the distribution resulting from the 'real' data. Secondly, the wilcoxon's test results are returned.

### Details

* If samples' ID defined in `data` and `data_ref` are not the same an inner join is effected according Samples' ID.
* The test assume that data are independent.
* Data are scaled before to be ploted.
* **Becareful** the calcul could be long if the number of simulations is high ($n>30$).

### See also 

`CP_main`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


## Map of CP values `CP_map`

### Description 

This function allows to display samples' CP value on 2D projection.

### Usage

`CP_map <- function(data_CP, data_coords, listK, Title = NULL)` 

### Arguments

* **data_CP** : data frame containing samples' ID, their CP values and the k levels associated such as :

| Sample_ID | K          | CP1     |
|-----------|------------|---------|
| MYID      | 1Kst_level | CP1_id1 |


* **data_coords** : data frame of coordinates in 2D.

* **list_K** : list of k levels according the ones CP values are calculated.

* **Title** : optional argument defining the graphics title.

### Value 

Plotly graphics.

### Details

Plotly could slow down the R session. 

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


## Centrality preservation significance test using a Monte Carlo approch `CP_monte_carlo`

### Description 

This function allows to test if  given a k level the centrality preservation  of a projection is more conservative than what could be expected on random projection. This test is realized according a simulation procedure, using a Monte Carlo approch, like this the resulting *p_value* correspond to the proportion of simulations that allowed to abtain a mean of $DCP_k$ values lower than the one determined using the 'real' projection. 

### Usage

`CP_monte_carlo(data, data_ref, k_val, n=100)` 

### Arguments

* **data** : data frame containing samples' ID, and their coordinates possibly defined in $\mathbb{R}^n$ such as :

| Sample_ID | x          | y       | ...     |
|-----------|------------|---------|---------|
| MYID      | ...        |...      |...      |


* **data_ref** : data frame containing samples' of coordinates, as previously defined. This data frame could be seen as the reference one, since it is used to calculated the $DCP_k$ values on the 'real' data and on similutaions.

* **k_val** : Level k from which the test is done.

* **n** : optional argument defining the number of simulations.

### Value 

Statistic results of the Monte Carlo procedure.

### Details

Contrary to the function `CP_permutation_test`, the number of simulation could be higher since the test is realize for one k level.






[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)
[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)
[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)



# Sequence difference view

## Sequence difference view calculation `Seq_calcul`

### Description 
 
This function allows to calculate the sequence diffeence ($SD$) view metrics. For a point $i$  the formula is :
$$SD_k(i) = \frac{1}{2} \sum_{j \in V^l_k(i)}(k-\rho^l_i(j)).|\rho^l_i(j)-\rho^h_i(j)|+  \frac{1}{2} \sum_{j \in V^h_k(i)}(k-\rho^h_i(j)).|\rho^l_i(j)-\rho^h_i(j)| $$

where $\rho^d_i(j)$ is the rank of $j$ in the neighborhood of $i$ at the level $k$ in the space $d$, and $V^d_k(i)$ is the $k-$neighborhood of $i$ in the space $d$. This metric penalizes the non preservation of $j$'s rank between $D^l$ and $D^h$, and weights this penalization according $ij$'s closeness.

### Usage

`Seq_calcul <- function(l_data, dataRef, listK)`

### Arguments

* **l_data** : list of data frame whose structure is like  :

| Sample_ID | x       | y        | ... |
|-----------|---------|----------|-----|
| MYID      | x_coord | y_coords | ... |

These data frames contain samples' coordinates which could be defined in $\mathbb{R^n}$.

* **dataRef** : reference data frame whose structure was defined above.  

* **listK** : list k values

### Details 

* A inner join on samples' ID is effected if they differs between the different data frames.
* Calculations use a parallel computing  according the levels $k$. 

### Value 

A list of containing $l$ element is returned, where $l$ is the number of data frame in `l_data`.
Each element contains $n$ SQ values, where $n$ is the number of common samles' ID.


[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Main function for sequence difference view `Seq_main`

### Description 
 
This function allows to calculate $SD$ values for several data frames and for differents k levels. Distributions of  
means $SD$ values by levels $k$ could be plot. Finally statistic tests could be computed if at least two $SD$ vectors were calculated.

### Usage

`Seq_main <- function(l_data, dataRef, listK, colnames_res_df = NULL , filename = NULL , graphics = FALSE, stats = FALSE)`

### Arguments

* **l_data** : list of data frame whose structure is :

| Sample_ID | x       | y        | ... |
|-----------|---------|----------|-----|
| MYID      | x_coord | y_coords | ... |

These data frames contain samples' coordinates which could be defined in $\mathbb{R^n}$.


* **dataref** : data frame of reference whose strucuture is the same as define above. 

* **listK** : list k values

* **colnames_res_df** : This optional argument allows to specify colnames of the returned data frame and also plot's legend if it was computed. If this argument is unsecified then the default values will be set to : V1,V2, ..., Vn (where $n$ is the length of `l_data`). The reference data frame will be named "REF".

* **filename** : This optional arguement allows to defined the filename on which results will be written. If this argument is unspecified then results will be returned and not written. If users choose a filename that ever exits in the current directory a incrementation to the filename will be done.

* **graphics** : This boolean argument allows to computes plot. The plot represents means of $SD$ values for the different $k$ levels and for the different data frames in `l_data`.

* **stats** :  This option allows to run statistic tests, it is available only if the number of defines method is higher at least equal to two, (*i.e* `l_data`'s length is $\geq 2$). If only two data frames were given as input via the `l_data`  then a Wilcoxon test will be computed to compare the distribution of the the means by k levels of absolute differences between $SD$ values. If more than two methods were defined then  Wilcoxon paired tests are done.

### Details 

* A inner join on samples' ID is effected if those differs between the different data frames.
* Statistical tests are realized under the assumption of the non independance of data.
* Data are scaled before to be plot.

### Value 

According options activated the return list contains the following elements :

* **Seq_df** : data frame containing a column with the samples' Id, a column correspoding to the levels k, and $n$ colunms of $SD$ values. This data frame is written is a `filename` is defined.

* **Seq_mean_by_k** : data frame containing the means of $SD$ values by level $k$, and this each data frame defined in `l_data`.

* **WT** : Wilcoxon test's results.

* **pWT** :  Matrix of Wilcoxon paired tests' p.value.

* **graphics** : GGplot if the graphic was computed.



[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Graphic of means of sequence difference values by k values `Seq_graph_by_k`

### Description 
 
This function displays the graphic of means of sequence difference values by k values.

### Usage

`Seq_graph_by_k  <-function (data_Seq, Names=NULL, list_col=NULL, data_diff_mean_K = NULL,  log = FALSE)`

### Arguments

* **data_Seq** : data frame of sequence difference values structured such as :

| Sample_ID | K          | CP1     |
|-----------|------------|---------|
| MYID      | 1Kst_level | CP1_id1 |


* **Names** : optional argument allowing to precise legend labels. If this argument is unprecised lengend labels are equal to `data_Seq`'s colnames.


* **list_col** : this optional argument allows to speficy colors, otherwise the list of colors previously defined is used.

* **data_diff_mean_K** : optional data frame contining means of SQ values by K level. If this argument is precised then means are not calculated. 

* **log** : optional boolean argument, if it is turned to TRUE the representations will be done according a logarithmic scale.

### Value 

A ggplot object is returned.

## Details 

If means by k are not given as input then data will be automatically scaled. Otherwise users have to scale their data.

### See also

`Seq_main`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Sequence difference values permutation test `seq_permutation_test`

### Description 
 
Then this function tets the following hypothesis :

$SD$ values calculated on real data have the same mean ranks than the ones expected if data coordinates where randomly distributed.
In order to do this $n$ simulations are realized. Acccording these simulations means by k values are calculated. Finally wilcoxon test is effected to compare if the mean ranks obtained on random distribution is equal to the one obtained on the 'real data'.

### Usage

`seq_permutation_test <- function(data, data_ref, list_K, n=30, graph = TRUE)`

### Arguments

* **data** : data frame defining such as :

| Sample_ID | x       | y        | ... |
|-----------|---------|----------|-----|
| MYID      | x_coord | y_coords | ... |


* **data_ref** : reference data frame whose structure is the same as above.

* **listK** : list k values.

* **n** : number of simulations.

* **graph** : optional boolean argument, if this argument is TRUE, simulations resulting graphic is computed.

### Value 

This function returns a list containing the Wilcoxon test's results and a graphic.

### Details 

Data are scaled before to be plot.

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%% MERGING TOOL  %%%%%%%%%%%%%%%%%%%%%%%%%%%%)

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)
[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)
[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)
[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

# Spatial autocorrelation

## Moran index main function `moran_I_main`

### Description 
 
This function allows to calculate Moran Indexes, which is a spatial autocorrelation metric. Values are calculated for several variables according several projection and for differents k levels. Graphics of Moran Indexes distribution for each variable, could be displayed. Finally the significance tests are computed according the Monte Carlo procedure. The hypothesis is : Does the observed spatial autocorrelation is higher than the one expected for random spatial distributions ?

### Usage

`moran_I_main <-function(l_coords_data , spatial_att, listK, nsim = 500, Stat=FALSE, Graph = FALSE, methods_name = NULL)`

### Arguments

* **l_coords_data** : list of coordinates data frames whose structure is :

| Sample_ID | x       | y        | ... |
|-----------|---------|----------|-----|
| MYID      | x_coord | y_coords | ... |

These data frames contain samples' coordinates which could be defined in $\mathbb{R^n}$.


* **spatial_att** : data frame which contains variables values.

| Sample_ID | Variable1 | Variable2 | ... |
|-----------|-----------|-----------|-----|
| MYID      | V1_myid   | V2_myid   | ... |

* **listK** : list k values

* **nsim** : number of simulations for the significance test. 

* **Stat** : optional boolean argument, if this argument is set to TRUE, then the significance test will be calculated.

* **Graph** : optional boolean argument,  if this argument is set to TRUE, then the graphic of Moran Index distributions is drawn. This graphic depicts Moran Indexes distributions for each variable.

* **methods_name** : optional argument, that could contain a list of characters, in order to define the plot's legend.
 
### Details 

Moran Idexes calculation use parallel computing.
A inner join on samples' ID is effected if those differs between the different data frames.
Moran Indexes and statistics for dimension higher than two are computed according `moran_index_HD` and `moran_stat_HD`functions.

### Value 

According options activated the return list contains the following elements :

* **MI_array** : 3D array containing Moran Index for each projection in row $i$, each variable in colunm $j$ and each $k$ level.

* **MS_array** : 3D array containing Moran Significance tests' p.value for each projection in row $i$, each variable in colunm $j$ and each $k$ level.

* **Graph** : A ggplot is printed if the option is activated.

### See also 
`moran_index_HD`, `moran_stat_HD` and `moran_I_scatter_plot`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)

## Calcul of Moran Indexes for high dimensional data `moran_index_HD `

### Description 
 
This function allows to calculate Moran Indexes for high dimensional data by generalizing the process effected in 2D. In order to get Moran Indexes the $k-$nearest neighbors are defined for each sample according the brute method of knn algorithm. This $k-$nearest neighbors is use to define the spatial weights matrix. Then Moran Indexes are computed classically. 

### Usage

`moran_index_HD <- function(data, spatial_att, K, merge = TRUE)`

### Arguments

* **data** : data frame defining such as :

| Sample_ID | x        | y        | z        | ... |
|-----------|----------|----------|----------|-----|
| MYID      | x_coords | y_coords | z_coords | ... |


* **spatial_att** : data frame which contains variables values.

| Sample_ID | Variable1 | Variable2 | ... |
|-----------|-----------|-----------|-----|
| MYID      | V1_myid   | V2_myid   | ... |

* **K** : numeric argument defining k level.

* **merge** : optional boolean argument that allows to checked if `spatial_att` and `datta` contains the same samples' ID. If samples' ID differs then an inner join will be done, otherwise the program doesn't cope the potential errors resulting of differences between the `Sample_ID` contained in `spatial_att` and `data`.

### Value 

Moran Index (numeric value).

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


## Moran significance test for high dimensional data `moran_stat_HD`


### Description 
 
Singnificance test computes according the Monte Carlo procedure. Like this $n$ simulations are done, at each iteration the vector of the variable of interest is shuffled, and then Moran Indexes are clculatated using the `moran_index_HD` function. Finally the rank of the observed Moran Index calculated for  the real projection is computed to infer an p.value. This p.value is the proportion of Moran Indexes obtained according random data that are greater to the one obtain according the "real projection". 

### Usage

`moran_stat_HD <- function(data, K, spatial_att, obs_moran_I, nsim = 99)`

### Arguments

* **data** : data frame defining such as :

| Sample_ID | x        | y        | z        | ... |
|-----------|----------|----------|----------|-----|
| MYID      | x_coords | y_coords | z_coords | ... |


* **K** : numeric argument defining a level $k$.

* **spatial_att** : data frame, which contains **a** attribute of interest, whose the structure is defined below.

| Sample_ID | Variable1 | 
|-----------|-----------|
| MYID      | V1_myid   |      



* **obs_moran_I** : observed moran Index computed according the real spatial distribution of the variable.

* **nsim** : number of simulations.

### Value 

Moran Significance test p.value. 

### See also 

`moran_I_main`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


## Graphic of Moran Indexes for each variable and each method `moran_I_scatter_plot`

### Description 
 
This function allows to displays the plot of Moran Indexes for each variable and and each method, a scatter plot is generated if Moran Indexes are defined for only one k level otherwise boxplots are generated. 

### Usage

`moran_I_scatter_plot <- function(data, Xlab = NULL, Ylab=NULL, Title= NULL)`

### Arguments

* **data** : array containing Moran Indexes whose the structure is the following :

|         | Varaible1 | Varaible2 | Varaible3 | ... |
|---------|-----------|-----------|-----------|-----|
| Method1 | MI_v1_m1  | MI_v2_m1  | MI_v3_m1  | ... |
| Method2 | MI_v1_m2  | ...       | ...       | ... |
| ...     | ...       | ...       | ...       | ... |


This array is in $|k|$ dimension, according the number of $k$ level for which Moran Indexes where calculated.


* **Xlab** : this optional argument is used to define the x-axis label.

* **Ylab** : this optional argument is used to define the y-axis label.

* **Title** : This optional argument is used to define the plot title.

### Value 

This function return a ggplot object.

### See also

`moran_I_main`

[comment]: <> (%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%)


## Graphic of Moran Indexes for each variable by k level `moran_I_scatter_plot_by_k`

### Description 
 
This function allows to displays the plot of Moran Indexes for each variable for the different k levels, one graphic by method will be generated. This representation could complete the one given by `moran_I_scatter_plot`.

### Usage

`moran_I_scatter_plot_by_k <- function(data, Xlab = NULL, Ylab=NULL, Title= NULL)`

### Arguments

